export const ACTION_TYPES =
{
    REQ_ISSUES: 'REQ_ISSUES',
    REC_ISSUES: 'REC_ISSUES',
    REQ_ISSUE: 'REQ_ISSUE',
    REC_ISSUE: 'REC_ISSUE',
    REQ_COMMENTS: 'REQ_COMMENTS',
    REC_COMMENTS: 'REC_COMMENTS',
    SHOW_LIST: 'SHOW_LIST',
    SAVE_LINKS: 'SAVE_LINKS'
}